---
title: "viz_ii"
author: "Jianing Chen"
date: "2024-09-26"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork )
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") %>%
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

## labels

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (c)",
    y = "Maximum daily temperature (c)",
    caption = "Data from ronoaa package; temperatures in 2017"
  )
```
## Scales

start with the same plot; x and y scales.

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (c)",
    y = "Maximum daily temperature (c)",
    caption = "Data from ronoaa package; temperatures in 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    ## trans = "sqrt"
    ## "log"
    position = "right"
  )

```
Look at color scales.

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (c)",
    y = "Maximum daily temperature (c)",
    caption = "Data from ronoaa package; temperatures in 2017"
  ) +
  ##scale_color_hue(
    ##name = "location", 
    ##h = c(100,300))
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
  
```
## Themes

shift the legend.

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (c)",
    y = "Maximum daily temperature (c)",
    caption = "Data from ronoaa package; temperatures in 2017"
  )+
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)+
  theme(legend.position = "bottom")

```

Change the overall theme.

```{r}
weather_df %>%
  ggplot(aes(x=tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (c)",
    y = "Maximum daily temperature (c)",
    caption = "Data from ronoaa package; temperatures in 2017"
  )+
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)+
    theme_minimal() +
     theme(legend.positions = "bottom")
     ##theme_classic()
     ##ggthemes::theme_economist()
     ##ggthemes::theme_excel()
```

## Setting options

```{r,eval=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill="viridis"
)
scale_color_discrete= scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```




